ProgRep: Progress_Report.tex
	pdflatex Progress_Report
	bibtex Progress_Report1
	bibtex Progress_Report1
	pdflatex Progress_Report
	pdflatex Progress_Report
	pdftotext Progress_Report.pdf
	wc -w Progress_Report.txt

clean:
	git clean -xdf

