ProgRep: Dissertation.tex
	pdflatex Dissertation
	bibtex Dissertation1
	bibtex Dissertation1
	pdflatex Dissertation
	pdflatex Dissertation
	pdftotext Dissertation.pdf
	wc -w Dissertation.txt

clean:
	git clean -xdf

